---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cicd
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    tier: postgreSQL
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: cicd
  labels:
    app: postgres
spec:
  template:
    metadata:
      labels:
        app: postgres
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgresadmin
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_PASSWORD
              value: admin123
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres
        hostPath:
          path: /mnt/kube-data/postgres
          type: Directory
